title: NightOwl code real
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "SomeHNightOwlacker"
  email: "nightowlcoder@outlook.com"
  url: "http://nightowlcoder.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NightOwlCoder"
year : "2019"

theme: jekyll-theme-hacker